# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schedule_interview.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

import smtplib

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from PyQt5 import QtCore, QtGui, QtWidgets
from email_mess import Ui_Dialog
class Ui_MainWindow(object):
    def __init__(self,main_win,short_ui):
        self.main_win=main_win
        self.short_ui=short_ui
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 579)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/imgonline-com-ua-resize-CTsWWNaYCcTcOI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.schedule = QtWidgets.QFrame(self.centralwidget)
        self.schedule.setFrameShape(QtWidgets.QFrame.Box)
        self.schedule.setFrameShadow(QtWidgets.QFrame.Raised)
        self.schedule.setObjectName("schedule")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.schedule)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.schedule_interview = QtWidgets.QLabel(self.schedule)
        font = QtGui.QFont()
        font.setFamily("Nimbus Sans L")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.schedule_interview.setFont(font)
        self.schedule_interview.setFrameShape(QtWidgets.QFrame.Box)
        self.schedule_interview.setObjectName("schedule_interview")
        self.gridLayout_4.addWidget(self.schedule_interview, 0, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.schedule)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.date = QtWidgets.QLabel(self.frame)
        self.date.setObjectName("date")
        self.gridLayout_2.addWidget(self.date, 0, 3, 1, 1)
        self.u_name = QtWidgets.QLabel(self.frame)
        self.u_name.setObjectName("u_name")
        self.gridLayout_2.addWidget(self.u_name, 0, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.o_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.o_7.setFont(font)
        self.o_7.setObjectName("o_7")
        self.horizontalLayout_10.addWidget(self.o_7)
        self.u_name_l_7 = QtWidgets.QLineEdit(self.frame)
        self.u_name_l_7.setObjectName("u_name_l_7")
        self.horizontalLayout_10.addWidget(self.u_name_l_7)
        self.e_mail_l_7 = QtWidgets.QLineEdit(self.frame)
        self.e_mail_l_7.setObjectName("e_mail_l_7")
        self.horizontalLayout_10.addWidget(self.e_mail_l_7)
        self.date_l_7 = QtWidgets.QLineEdit(self.frame)
        self.date_l_7.setObjectName("date_l_7")
        self.horizontalLayout_10.addWidget(self.date_l_7)
        self.time_l_7 = QtWidgets.QLineEdit(self.frame)
        self.time_l_7.setObjectName("time_l_7")
        self.horizontalLayout_10.addWidget(self.time_l_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 6, 0, 1, 5)
        self.line_2 = QtWidgets.QHBoxLayout()
        self.line_2.setObjectName("line_2")
        self.o_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.o_2.setFont(font)
        self.o_2.setObjectName("o_2")
        self.line_2.addWidget(self.o_2)
        self.u_name_l_2 = QtWidgets.QLineEdit(self.frame)
        self.u_name_l_2.setObjectName("u_name_l_2")
        self.line_2.addWidget(self.u_name_l_2)
        self.e_mail_l_2 = QtWidgets.QLineEdit(self.frame)
        self.e_mail_l_2.setObjectName("e_mail_l_2")
        self.line_2.addWidget(self.e_mail_l_2)
        self.date_l_2 = QtWidgets.QLineEdit(self.frame)
        self.date_l_2.setObjectName("date_l_2")
        self.line_2.addWidget(self.date_l_2)
        self.time_l_2 = QtWidgets.QLineEdit(self.frame)
        self.time_l_2.setObjectName("time_l_2")
        self.line_2.addWidget(self.time_l_2)
        self.gridLayout_2.addLayout(self.line_2, 2, 0, 1, 5)
        self.line_1 = QtWidgets.QHBoxLayout()
        self.line_1.setObjectName("line_1")
        self.o_1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.o_1.setFont(font)
        self.o_1.setObjectName("o_1")
        self.line_1.addWidget(self.o_1)
        self.u_name_l = QtWidgets.QLineEdit(self.frame)
        self.u_name_l.setObjectName("u_name_l")
        self.line_1.addWidget(self.u_name_l)
        self.e_mail_l = QtWidgets.QLineEdit(self.frame)
        self.e_mail_l.setObjectName("e_mail_l")
        self.line_1.addWidget(self.e_mail_l)
        self.date_l = QtWidgets.QLineEdit(self.frame)
        self.date_l.setObjectName("date_l")
        self.line_1.addWidget(self.date_l)
        self.time_l = QtWidgets.QLineEdit(self.frame)
        self.time_l.setObjectName("time_l")
        self.line_1.addWidget(self.time_l)
        self.gridLayout_2.addLayout(self.line_1, 1, 0, 1, 5)
        self.time = QtWidgets.QLabel(self.frame)
        self.time.setObjectName("time")
        self.gridLayout_2.addWidget(self.time, 0, 4, 1, 1)
        self.e_mail = QtWidgets.QLabel(self.frame)
        self.e_mail.setObjectName("e_mail")
        self.gridLayout_2.addWidget(self.e_mail, 0, 2, 1, 1)
        self.s_n = QtWidgets.QLabel(self.frame)
        self.s_n.setObjectName("s_n")
        self.gridLayout_2.addWidget(self.s_n, 0, 0, 1, 1)
        self.line_5 = QtWidgets.QHBoxLayout()
        self.line_5.setObjectName("line_5")
        self.o_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.o_6.setFont(font)
        self.o_6.setObjectName("o_6")
        self.line_5.addWidget(self.o_6)
        self.u_name_l_6 = QtWidgets.QLineEdit(self.frame)
        self.u_name_l_6.setObjectName("u_name_l_6")
        self.line_5.addWidget(self.u_name_l_6)
        self.e_mail_l_6 = QtWidgets.QLineEdit(self.frame)
        self.e_mail_l_6.setObjectName("e_mail_l_6")
        self.line_5.addWidget(self.e_mail_l_6)
        self.date_l_6 = QtWidgets.QLineEdit(self.frame)
        self.date_l_6.setObjectName("date_l_6")
        self.line_5.addWidget(self.date_l_6)
        self.time_l_6 = QtWidgets.QLineEdit(self.frame)
        self.time_l_6.setObjectName("time_l_6")
        self.line_5.addWidget(self.time_l_6)
        self.gridLayout_2.addLayout(self.line_5, 5, 0, 1, 5)
        self.line_3 = QtWidgets.QHBoxLayout()
        self.line_3.setObjectName("line_3")
        self.o_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.o_4.setFont(font)
        self.o_4.setObjectName("o_4")
        self.line_3.addWidget(self.o_4)
        self.u_name_l_4 = QtWidgets.QLineEdit(self.frame)
        self.u_name_l_4.setObjectName("u_name_l_4")
        self.line_3.addWidget(self.u_name_l_4)
        self.e_mail_l_4 = QtWidgets.QLineEdit(self.frame)
        self.e_mail_l_4.setObjectName("e_mail_l_4")
        self.line_3.addWidget(self.e_mail_l_4)
        self.date_l_4 = QtWidgets.QLineEdit(self.frame)
        self.date_l_4.setObjectName("date_l_4")
        self.line_3.addWidget(self.date_l_4)
        self.time_l_4 = QtWidgets.QLineEdit(self.frame)
        self.time_l_4.setObjectName("time_l_4")
        self.line_3.addWidget(self.time_l_4)
        self.gridLayout_2.addLayout(self.line_3, 3, 0, 1, 5)
        self.line_4 = QtWidgets.QHBoxLayout()
        self.line_4.setObjectName("line_4")
        self.o_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.o_5.setFont(font)
        self.o_5.setObjectName("o_5")
        self.line_4.addWidget(self.o_5)
        self.u_name_l_5 = QtWidgets.QLineEdit(self.frame)
        self.u_name_l_5.setObjectName("u_name_l_5")
        self.line_4.addWidget(self.u_name_l_5)
        self.e_mail_l_5 = QtWidgets.QLineEdit(self.frame)
        self.e_mail_l_5.setObjectName("e_mail_l_5")
        self.line_4.addWidget(self.e_mail_l_5)
        self.date_l_5 = QtWidgets.QLineEdit(self.frame)
        self.date_l_5.setObjectName("date_l_5")
        self.line_4.addWidget(self.date_l_5)
        self.time_l_5 = QtWidgets.QLineEdit(self.frame)
        self.time_l_5.setObjectName("time_l_5")
        self.line_4.addWidget(self.time_l_5)
        self.gridLayout_2.addLayout(self.line_4, 4, 0, 1, 5)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.send_email = QtWidgets.QPushButton(self.schedule)
        self.send_email.setObjectName("send_email")
        self.send_email.clicked.connect(self.send_ma)
        self.horizontalLayout_17.addWidget(self.send_email)
        self.gridLayout_4.addLayout(self.horizontalLayout_17, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.schedule, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def send_ma(self):
        #get all the username ,email,job_name,date,time list
        username=[]
        email=[]
        
        date=[]
        time=[]
        username.append(self.u_name_l.text())
        username.append(self.u_name_l_2.text())
        username.append(self.u_name_l_4.text())
        username.append(self.u_name_l_5.text())
        username.append(self.u_name_l_6.text())
        username.append(self.u_name_l_7.text())
        date.append(self.date_l.text())
        date.append(self.date_l_2.text())
        date.append(self.date_l_4.text())
        date.append(self.date_l_5.text())
        date.append(self.date_l_6.text())
        date.append(self.date_l_7.text())
        email.append(self.e_mail_l.text())
        email.append(self.e_mail_l_2.text())
        email.append(self.e_mail_l_4.text())
        email.append(self.e_mail_l_5.text())
        email.append(self.e_mail_l_6.text())
        email.append(self.e_mail_l_7.text())

        time.append(self.time_l.text())
        time.append(self.time_l_2.text())
        time.append(self.time_l_4.text())
        time.append(self.time_l_5.text())
        time.append(self.time_l_6.text())
        time.append(self.time_l_7.text())
        
     
        print("ok")
        print(username)
        for user,emai,dat,tim in zip(username,email,date,time):
            print(user)
            print("lucky")
            if(user!=''):
                msg = MIMEMultipart()
                msg["Subject"] = "Interview Invitation"
                msg["From"] = "luckyagarwal459@gmail.com"
                msg["To"] = emai
                body = MIMEText("Dear " + user +",\
                \nAs a result of your application for the position of Software Developer, I would like to invite you to attend an interview on " + dat + ", at " + tim +" at our office in Quincy, Massachusetts.\
                You will have an interview with the department manager, Edie Wilson. The interview will last about 45 minutes. Please bring three references as well as a copy of your drivers license to the interview.\
                \nIf the date or time of the interview is inconvenient, please contact me by phone (518-555-5555) or email (tgunn@randall.com) to arrange another appointment. We look forward to seeing you.\
                \nBest regards,\
                \nLucky agarwal\
                \n_______\
                \nlucky agarwal\
                \nAdministrative Director\
                \nRandall & Associates\
                ")
                msg.attach(body)
                smtp = smtplib.SMTP('smtp.gmail.com', 587)
                smtp.starttls() 
                smtp.login("luckyagarwal459@gmail.com", "ykcul@123") 
                smtp.sendmail(msg["From"], msg["To"].split(","), msg.as_string())
                print("email sent")
                smtp.quit()        
        print("success")   
        self.success()
        
    def success(self):
        self.main_win.hide()
        self.short_ui.hide()
        self.Dialog = QtWidgets.QDialog()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()
        
        
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Schedule Interview"))
        self.schedule_interview.setText(_translate("MainWindow", "Schedule Interview"))
        self.date.setText(_translate("MainWindow", "Date"))
        self.u_name.setText(_translate("MainWindow", " User"))
        self.o_7.setText(_translate("MainWindow", "6."))
        self.o_2.setText(_translate("MainWindow", "2."))
        self.o_1.setText(_translate("MainWindow", "1."))
        self.time.setText(_translate("MainWindow", "Time"))
        self.e_mail.setText(_translate("MainWindow", "E-mail"))
        self.s_n.setText(_translate("MainWindow", "S.N       "))
        self.o_6.setText(_translate("MainWindow", "5."))
        self.o_4.setText(_translate("MainWindow", "3."))
        self.o_5.setText(_translate("MainWindow", "4."))
        self.send_email.setText(_translate("MainWindow", "Send E-mail"))

