# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from shortlisted import Ui_shortlisted_candidate
from Interview_results import Ui_Interview_results
from creatd_vacant import Ui_vacant
import database

class Ui_Window_1(object):
    def setupUi(self, Window_1):
        Window_1.setObjectName("Window_1")
        Window_1.resize(640, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/965230-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Window_1.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Window_1)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.interview_dash = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Noto Kufi Arabic")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.interview_dash.setFont(font)
        self.interview_dash.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.interview_dash.setObjectName("interview_dash")
        self.verticalLayout_4.addWidget(self.interview_dash)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.shortlisted)
        self.verticalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.shortlisted_final)
        self.verticalLayout_4.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create_vacancies = QtWidgets.QFrame(self.centralwidget)
        self.create_vacancies.setFrameShape(QtWidgets.QFrame.Box)
        self.create_vacancies.setFrameShadow(QtWidgets.QFrame.Raised)
        self.create_vacancies.setObjectName("create_vacancies")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.create_vacancies)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.c_vacan = QtWidgets.QLabel(self.create_vacancies)
        font = QtGui.QFont()
        font.setFamily("Noto Kufi Arabic")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c_vacan.setFont(font)
        self.c_vacan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.c_vacan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.c_vacan.setObjectName("c_vacan")
        self.verticalLayout_3.addWidget(self.c_vacan)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sd = QtWidgets.QLabel(self.create_vacancies)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.sd.setFont(font)
        self.sd.setFrameShape(QtWidgets.QFrame.Box)
        self.sd.setObjectName("sd")
        self.verticalLayout.addWidget(self.sd)
        self.it = QtWidgets.QLabel(self.create_vacancies)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.it.setFont(font)
        self.it.setFrameShape(QtWidgets.QFrame.Panel)
        self.it.setObjectName("it")
        self.verticalLayout.addWidget(self.it)
        self.ds = QtWidgets.QLabel(self.create_vacancies)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ds.setFont(font)
        self.ds.setFrameShape(QtWidgets.QFrame.Panel)
        self.ds.setObjectName("ds")
        self.verticalLayout.addWidget(self.ds)
        self.fa = QtWidgets.QLabel(self.create_vacancies)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.fa.setFont(font)
        self.fa.setFrameShape(QtWidgets.QFrame.Panel)
        self.fa.setObjectName("fa")
        self.verticalLayout.addWidget(self.fa)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sd_l = QtWidgets.QLineEdit(self.create_vacancies)
        self.sd_l.setObjectName("sd_l")
        self.verticalLayout_2.addWidget(self.sd_l)
        self.it_l = QtWidgets.QLineEdit(self.create_vacancies)
        self.it_l.setObjectName("it_l")
        self.verticalLayout_2.addWidget(self.it_l)
        self.ds_l = QtWidgets.QLineEdit(self.create_vacancies)
        self.ds_l.setObjectName("ds_l")
        self.verticalLayout_2.addWidget(self.ds_l)
        self.fa_l = QtWidgets.QLineEdit(self.create_vacancies)
        self.fa_l.setObjectName("fa_l")
        self.verticalLayout_2.addWidget(self.fa_l)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 216, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.create_frame = QtWidgets.QFrame(self.create_vacancies)
        self.create_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.create_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.create_frame.setObjectName("create_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.create_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.create_frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.create_vacant)
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout_3.addWidget(self.create_frame)
        self.horizontalLayout.addWidget(self.create_vacancies)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        Window_1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Window_1)
        self.statusbar.setObjectName("statusbar")
        Window_1.setStatusBar(self.statusbar)

        self.retranslateUi(Window_1)
        QtCore.QMetaObject.connectSlotsByName(Window_1)
     
    def create_vacant(self):
        Software_developer=self.sd_l.text()
        IT=self.it_l.text()
        Date_scientist=self.ds_l.text()
        Finance_and_Accounting=self.fa_l.text()
        
        database.update_job_catgories_table("Software_developer",int(Software_developer))
        database.update_job_catgories_table("IT",int(IT))
        database.update_job_catgories_table("Date_scientist",int(Date_scientist))
        database.update_job_catgories_table("Finance_and_Accounting",int(Finance_and_Accounting))
        self.Dia = QtWidgets.QDialog()
        self.ui = Ui_vacant()
        self.ui.setupUi(self.Dia)
        self.Dia.show()
        
    def shortlisted_final(self):
        short=database.cor.execute("SELECT * FROM Interview_results")
        self.Ui_Interview= QtWidgets.QMainWindow()
        self.ui = Ui_Interview_results(short,self.Ui_Interview)
        self.ui.setupUi(self.Ui_Interview)
        self.Ui_Interview.show()   
        
    def shortlisted(self):
        short=database.cor.execute("SELECT * FROM shortlisted_candidate")
        self.Ui_shortlisted= QtWidgets.QMainWindow()
        self.ui = Ui_shortlisted_candidate(short,self.Ui_shortlisted)
        self.ui.setupUi(self.Ui_shortlisted)
        self.Ui_shortlisted.show()
        
    def retranslateUi(self, Window_1):
        _translate = QtCore.QCoreApplication.translate
        Window_1.setWindowTitle(_translate("Window_1", "Welcome"))
        self.interview_dash.setText(_translate("Window_1", "Interview Dashboard"))
        self.pushButton.setText(_translate("Window_1", "Shortlisted Candidate"))
        self.pushButton_2.setText(_translate("Window_1", "Final Result"))
        self.c_vacan.setText(_translate("Window_1", "Create Vacancies"))
        self.sd.setText(_translate("Window_1", "   Software developer"))
        self.it.setText(_translate("Window_1", "   IT"))
        self.ds.setText(_translate("Window_1", "   Date Scientist"))
        self.fa.setText(_translate("Window_1", "   Finance and Accounting"))
        self.pushButton_3.setText(_translate("Window_1", "Create"))